export { default as Header } from './common/Header';
export { default as Footer } from './common/Footer';
export { default as Title } from './main/Title';
export { default as Popup } from './main/Popup';
export { default as Articles } from './main/Articles';
export { default as Writers } from './main/Writers';
export { default as Keywords } from './main/Keywords';
export { default as MainSlider } from './main/MainSlider';
export { default as Writer } from './main/Writer';